version: "3.9"
services:

  # EDC Connector to simulate a dataspace participant acting as a data provider which is located in EU.
  service:
    container_name: service
    build:
      context: ../../../launchers/connector
      args:
        JVM_ARGS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    env_file:
      - service.env
    depends_on:
      - registration-service
    ports:
      - "9191:9191"
      - "8181:8181"
      - "5005:5005"
      - "7171:7171"
    volumes:
      - ../resources/self-description/service:/resources

  # EDC Connector to simulate a dataspace participant acting as a data consumer which is located in EU.
  versicherung:
    container_name: versicherung
    build:
      context: ../../../launchers/connector
      args:
        JVM_ARGS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006"
    env_file:
      - versicherung.env
    depends_on:
      - registration-service
    ports:
      - "9192:9191"
      - "8182:8181"
      - "5006:5006"
      - "7172:7171"
    volumes:
      - ../resources/self-description/versicherung:/resources

  # EDC Connector to simulate a dataspace participant acting as a consumer which is located in US.
  flughafen:
    container_name: flughafen
    build:
      context: ../../../launchers/connector
      args:
        JVM_ARGS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007"
    env_file:
      - flughafen.env
    depends_on:
      - registration-service
    ports:
      - "9193:9191"
      - "8183:8181"
      - "5007:5007"
      - "7173:7171"
    volumes:
      - ../resources/self-description/flughafen:/resources

  # Dataspace registration service authority.
  registration-service:
    container_name: registration-service
    build:
      # e.g. /home/user/RegistrationService/launcher
      context: ../../../launchers/registrationservice
      args:
        JVM_ARGS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5008"
    env_file: reg.env

    ports:
      - "8184:8184"
      - "8185:8181"
      - "5008:5008"
      - "7174:7171"
    volumes:
      - ../resources/self-description/registration-service:/resources

  # Data Dashboard (MVD UI) for participant service
  service-datadashboard:
    container_name: service-datadashboard
    build:
      context: ../../system-tests/DataDashboard
    volumes:
      - ../resources/appconfig/service:/usr/share/nginx/html/assets/config
    depends_on:
      service:
        condition: service_healthy
    ports:
      - "7080:80"
    profiles: [ "ui" ]

    # Data Dashboard (MVD UI) for participant versicherung

  versicherung-datadashboard:
    container_name: versicherung-datadashboard
    build:
      context: ../../system-tests/DataDashboard
    volumes:
      - ../resources/appconfig/versicherung:/usr/share/nginx/html/assets/config
    depends_on:
      versicherung:
        condition: service_healthy
    ports:
      - "7081:80"
    profiles: [ "ui" ]

  # Data Dashboard (MVD UI) for participant flughafen
  flughafen-datadashboard:
    container_name: flughafen-datadashboard
    build:
      context: ../../system-tests/DataDashboard
    volumes:
      - ../resources/appconfig/flughafen:/usr/share/nginx/html/assets/config
    depends_on:
      flughafen:
        condition: service_healthy
    ports:
      - "7082:80"
    profiles: [ "ui" ]
