version: "3.9"
services:

  # EDC Connector to simulate a dataspace participant acting as a data provider which is located in EU.
  controltower:
    container_name: controltower
    build:
      context: ../../../launchers/connector
      args:
        JVM_ARGS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    env_file:
      - controltower.env
    depends_on:
      - registration-service
    ports:
      - "9191:9191"
      - "8181:8181"
      - "5005:5005"
      - "7171:7171"
    volumes:
      - ../resources/self-description/controltower:/resources

  # EDC Connector to simulate a dataspace participant acting as a data consumer which is located in EU.
  bridge:
    container_name: bridge
    build:
      context: ../../../launchers/connector
      args:
        JVM_ARGS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006"
    env_file:
      - bridge.env
    depends_on:
      - registration-service
    ports:
      - "9192:9191"
      - "8182:8181"
      - "5006:5006"
      - "7172:7171"
    volumes:
      - ../resources/self-description/bridge:/resources

  # EDC Connector to simulate a dataspace participant acting as a consumer which is located in US.
  airplane:
    container_name: airplane
    build:
      context: ../../../launchers/connector
      args:
        JVM_ARGS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007"
    env_file:
      - airplane.env
    depends_on:
      - registration-service
    ports:
      - "9193:9191"
      - "8183:8181"
      - "5007:5007"
      - "7173:7171"
    volumes:
      - ../resources/self-description/airplane:/resources

  # Dataspace registration service authority.
  registration-service:
    container_name: registration-service
    build:
      # e.g. /home/user/RegistrationService/launcher
      context: ../../../launchers/registrationservice
      args:
        JVM_ARGS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5008"
    env_file: reg.env

    ports:
      - "8184:8184"
      - "8185:8181"
      - "5008:5008"
      - "7174:7171"
    volumes:
      - ../resources/self-description/registration-service:/resources

  # Data Dashboard (MVD UI) for participant controltower
  controltower-datadashboard:
    container_name: controltower-datadashboard
    build:
      context: ../../system-tests/DataDashboard
    volumes:
      - ../resources/appconfig/controltower:/usr/share/nginx/html/assets/config
    depends_on:
      controltower:
        condition: service_healthy
    ports:
      - "7080:80"
    profiles: [ "ui" ]

    # Data Dashboard (MVD UI) for participant bridge

  bridge-datadashboard:
    container_name: bridge-datadashboard
    build:
      context: ../../system-tests/DataDashboard
    volumes:
      - ../resources/appconfig/bridge:/usr/share/nginx/html/assets/config
    depends_on:
      bridge:
        condition: service_healthy
    ports:
      - "7081:80"
    profiles: [ "ui" ]

  # Data Dashboard (MVD UI) for participant airplane
  airplane-datadashboard:
    container_name: airplane-datadashboard
    build:
      context: ../../system-tests/DataDashboard
    volumes:
      - ../resources/appconfig/airplane:/usr/share/nginx/html/assets/config
    depends_on:
      airplane:
        condition: service_healthy
    ports:
      - "7082:80"
    profiles: [ "ui" ]
