version: "3.9"
services:

  # EDC Connector to simulate a dataspace participant acting as a data provider which is located in EU.
  service:
    container_name: service
    build:
      context: ../launchers/connector
      args:
        JVM_ARGS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    environment:
      EDC_DSP_CALLBACK_ADDRESS: http://service:8282/api/dsp
      EDC_CONNECTOR_NAME: service
      EDC_PARTICIPANT_ID: did:web:did-server:service

      EDC_BLOBSTORE_ENDPOINT_TEMPLATE: "http://azurite:10000/%s"
      EDC_IDENTITY_DID_URL: did:web:did-server:service
      EDC_VAULT: /resources/vault/service/service-vault.properties
      EDC_KEYSTORE: /resources/vault/service/service-keystore.jks
      EDC_SELF_DESCRIPTION_DOCUMENT_PATH: /resources/self-description/service/sdd.json
      EDC_KEYSTORE_PASSWORD: test123
      EDC_API_AUTH_KEY: ApiKeyDefaultValue
      EDC_IAM_DID_WEB_USE_HTTPS: "false"
      EDC_CATALOG_CACHE_EXECUTION_DELAY_SECONDS: 5
      EDC_CATALOG_CACHE_EXECUTION_PERIOD_SECONDS: 5
      EDC_CATALOG_CACHE_PARTITION_NUM_CRAWLERS: 5
      EDC_DATAPLANE_TOKEN_VALIDATION_ENDPOINT: http://service:8383/api/control/token
      REGISTRATION_SERVICE_API_URL: http://registration-service:8184/api/authority
      EDC_WEB_REST_CORS_ENABLED: "true"
      EDC_WEB_REST_CORS_HEADERS: "origin,content-type,accept,authorization,x-api-key"
    depends_on:
      - did-server
      - azurite
      - registration-service
    ports:
      - "9191:9191"
      - "8181:8181"
      - "5005:5005"
      - "7171:7171"
    volumes:
      - ./resources:/resources

  # EDC Connector to simulate a dataspace participant acting as a data consumer which is located in EU.
  versicherung:
    container_name: versicherung
    build:
      context: ../launchers/connector
      args:
        JVM_ARGS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006"
    environment:
      EDC_DSP_CALLBACK_ADDRESS: http://versicherung:8282/api/dsp
      EDC_CONNECTOR_NAME: versicherung
      EDC_PARTICIPANT_ID: did:web:did-server:versicherung

      EDC_BLOBSTORE_ENDPOINT_TEMPLATE: "http://azurite:10000/%s"
      EDC_IDENTITY_DID_URL: did:web:did-server:versicherung
      EDC_VAULT: /resources/vault/versicherung/versicherung-vault.properties
      EDC_KEYSTORE: /resources/vault/versicherung/versicherung-keystore.jks
      EDC_SELF_DESCRIPTION_DOCUMENT_PATH: /resources/self-description/versicherung/sdd.json
      EDC_KEYSTORE_PASSWORD: test123
      EDC_API_AUTH_KEY: ApiKeyDefaultValue
      EDC_IAM_DID_WEB_USE_HTTPS: "false"
      EDC_CATALOG_CACHE_EXECUTION_DELAY_SECONDS: 5
      EDC_CATALOG_CACHE_EXECUTION_PERIOD_SECONDS: 5
      EDC_CATALOG_CACHE_PARTITION_NUM_CRAWLERS: 5
      EDC_DATAPLANE_TOKEN_VALIDATION_ENDPOINT: http://versicherung:8383/api/control/token
      REGISTRATION_SERVICE_API_URL: http://registration-service:8184/api/authority
      EDC_WEB_REST_CORS_ENABLED: "true"
      EDC_WEB_REST_CORS_HEADERS: "origin,content-type,accept,authorization,x-api-key"
    depends_on:
      - did-server
      - azurite
      - registration-service
    ports:
      - "9192:9191"
      - "8182:8181"
      - "5006:5006"
      - "7172:7171"
    volumes:
      - ./resources:/resources

  # EDC Connector to simulate a dataspace participant acting as a consumer which is located in US.
  flughafen:
    container_name: flughafen
    build:
      context: ../launchers/connector
      args:
        JVM_ARGS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007"
    environment:
      EDC_DSP_CALLBACK_ADDRESS: http://flughafen:8282/api/dsp
      EDC_CONNECTOR_NAME: flughafen
      EDC_PARTICIPANT_ID: did:web:did-server:flughafen

      EDC_BLOBSTORE_ENDPOINT_TEMPLATE: "http://azurite:10000/%s"
      EDC_IDENTITY_DID_URL: did:web:did-server:flughafen
      EDC_VAULT: /resources/vault/flughafen/flughafen-vault.properties
      EDC_KEYSTORE: /resources/vault/flughafen/flughafen-keystore.jks
      EDC_SELF_DESCRIPTION_DOCUMENT_PATH: /resources/self-description/flughafen/sdd.json
      EDC_KEYSTORE_PASSWORD: test123
      EDC_API_AUTH_KEY: ApiKeyDefaultValue
      EDC_IAM_DID_WEB_USE_HTTPS: "false"
      EDC_CATALOG_CACHE_EXECUTION_DELAY_SECONDS: 5
      EDC_CATALOG_CACHE_EXECUTION_PERIOD_SECONDS: 5
      EDC_CATALOG_CACHE_PARTITION_NUM_CRAWLERS: 5
      EDC_DATAPLANE_TOKEN_VALIDATION_ENDPOINT: http://flughafen:8383/api/control/token
      REGISTRATION_SERVICE_API_URL: http://registration-service:8184/api/authority
      EDC_WEB_REST_CORS_ENABLED: "true"
      EDC_WEB_REST_CORS_HEADERS: "origin,content-type,accept,authorization,x-api-key"
    depends_on:
      - did-server
      - azurite
      - registration-service
    ports:
      - "9193:9191"
      - "8183:8181"
      - "5007:5007"
      - "7173:7171"
    volumes:
      - ./resources:/resources

  # Usages postman collections for initial data seeding to connectors.
  newman:
    container_name: newman
    image: postman/newman:ubuntu
    entrypoint: /bin/bash
    command: deployment/seed-data.sh
    volumes:
      - ../deployment/:/deployment
    working_dir: /
    environment:
      API_KEY: ApiKeyDefaultValue
      EDC_HOST: service:versicherung:flughafen
      ASSETS_STORAGE_ACCOUNT: serviceassets:versicherungassets:flughafenassets
      PARTICIPANT_ID: service:versicherung:flughafen
    depends_on:
      service:
        condition: service_healthy
      versicherung:
        condition: service_healthy
      flughafen:
        condition: service_healthy

  # A nginx based HTTP server to serve dataspace participants DIDs.
  did-server:
    container_name: did-server
    image: nginx
    volumes:
      - ./resources/webdid:/usr/share/nginx/html
    ports:
      - "7070:80"

  # Azure blob storage simulator.
  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - 10000:10000
    environment:
      AZURITE_ACCOUNTS: serviceassets:key1;versicherungassets:key2;flughafenassets:key3

  # Dataspace registration service authority.
  registration-service:
    container_name: registration-service
    build:
      #e.g. /home/user/RegistrationService/launcher
      context: ../launchers/registrationservice
      args:
        JVM_ARGS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5008"
    environment:
      JWT_AUDIENCE: http://registration-service:8184/api/authority
      EDC_IAM_DID_WEB_USE_HTTPS: "false"
      EDC_CONNECTOR_NAME: registration-service
      EDC_IDENTITY_DID_URL: did:web:did-server:registration-service
      EDC_SELF_DESCRIPTION_DOCUMENT_PATH: /resources/self-description/registration-service/sdd.json
      EDC_VAULT: /resources/vault/registration-service/registration-service-vault.properties
      EDC_KEYSTORE: /resources/vault/registration-service/registration-service-keystore.jks
      EDC_KEYSTORE_PASSWORD: test123
      EDC_ERROR_RESPONSE_VERBOSE: "true"
    ports:
      - "8184:8184"
      - "8185:8181"
      - "5008:5008"
      - "7174:7171"
    volumes:
      - ./resources:/resources

  # cli-tools to help setup MVD environment e.g. registering participant to authority.
  cli-tools:
    container_name: cli-tools
    build:
      context: ./resources/cli-tools
    volumes:
      - ./resources:/resources
      - ../resources:/common-resources
    depends_on:
      service:
        condition: service_healthy
      versicherung:
        condition: service_healthy
      flughafen:
        condition: service_healthy
      registration-service:
        condition: service_healthy

  # Data Dashboard (MVD UI) for participant service
  service-datadashboard:
    container_name: service-datadashboard
    build:
      context: ${MVD_UI_PATH}
    volumes:
      - ./resources/appconfig/service:/usr/share/nginx/html/assets/config
    depends_on:
      service:
        condition: service_healthy
    ports:
      - "7080:80"
    profiles: ["ui"]

      # Data Dashboard (MVD UI) for participant versicherung
  versicherung-datadashboard:
    container_name: versicherung-datadashboard
    build:
      context: ${MVD_UI_PATH}
    volumes:
      - ./resources/appconfig/versicherung:/usr/share/nginx/html/assets/config
    depends_on:
      versicherung:
        condition: service_healthy
    ports:
      - "7081:80"
    profiles: ["ui"]

  # Data Dashboard (MVD UI) for participant flughafen
  flughafen-datadashboard:
    container_name: flughafen-datadashboard
    build:
      context: ${MVD_UI_PATH}
    volumes:
      - ./resources/appconfig/flughafen:/usr/share/nginx/html/assets/config
    depends_on:
      flughafen:
        condition: service_healthy
    ports:
      - "7082:80"
    profiles: ["ui"]
